- .env.example
- backend/README.md
Add instruction to README to add a `.env` file before running Docker as well as a sample file.
> Example .env file for Docker

- docker-compose.override.yml
This PR fixes the hot reload functionality for the backend within the Docker container for local development.
> fix: enable hot reload for backend in Docker

- frontend/.env
- frontend/.env.example
`frontend/.env` was included in the original repo but it should not have been because we may want to switch ports on our local and not corrupt prod  Added `.env.example` in this directory 
> Remove frontend/.env

- frontend/src/components/Inquiries/InquiriesTable.tsx
- frontend/src/routes/_layout/inquiries.tsx
In order to unit test, each component needs to be in a separate component file. 
> InquiryTable in separate Component file

- README.md
I updated the original readme to provide clear instructions on how to set up and run our app. 
Closes #47 
[Link to Ticket](https://incredihire-academy.atlassian.net/browse/SR-41?atlOrigin=eyJpIjoiYjIwYTk1Y2ViYzVkNGU2Yjg1OGU5MjJlYmM3MDk2MTIiLCJwIjoiaiJ9)
> docs: Update project setup doc

- frontend/src/sum.ts
Sum.ts should not have been committed to repo in src/ directory.  Removing it now.
> remove sum.ts

- frontend/__tests__/inquiry/inquiries_table.test.tsx
- frontend/package.json
- frontend/src/client/models.ts
- frontend/src/components/Inquiries/InquiriesTable.tsx
- frontend/tsconfig.json
Add unit tests for listing inquiries.
[Link to Ticket](https://incredihire-academy.atlassian.net/jira/software/c/projects/SR/boards/3?selectedIssue=SR-47)
I added f/e unit tests for `InquiriesTable` component using jest and react-testing library.
Some changes I had to make:
* I had to change the payload type for Inquiry's `created_at` from Date to string, since it will be converted to JSON.
* I had to move `formatDate` function to be declared inside `InquiriesTable` component, so that I can mock the behavior of `formatDate` in my test.
* I mocked user's timezone as `America/Los_Angeles` for the test
> test: Add f/e unit tests for displaying inquiries table

- backend/app/tests/api/routes/schedule/test_post_schedule_api.py
> fix backend schedule test names

- frontend/src/components/Admin/AddUser.tsx
- frontend/src/components/Admin/EditUser.tsx
- frontend/src/components/Inquiries/AddInquiry.tsx
- frontend/src/components/Inquiries/InquiriesTable.columns.ts
- frontend/src/components/UserSettings/ChangePassword.tsx
- frontend/src/components/UserSettings/DeleteConfirmation.tsx
- frontend/src/components/UserSettings/UserInformation.tsx
- frontend/src/hooks/useCreateSchedule.ts
- frontend/src/routeTree.gen.ts
- frontend/src/routes/login.tsx
- frontend/src/routes/recover-password.tsx
- frontend/src/routes/reset-password.tsx
- frontend/src/routes/signup.tsx
- frontend/src/utils/index.ts
* I removed `utils/index.ts`
* I updated utility function import paths
[Link to Related Ticket](https://incredihire-academy.atlassian.net/jira/software/c/projects/SR/boards/3?selectedIssue=SR-104)
[Link to Related PR](https://github.com/Incredihire/Survey/pull/89)
> refactor: Update utility function import paths

- frontend/__tests__/common/FormModal.test.tsx
- frontend/src/components/Common/FormModal.tsx
- frontend/src/components/Common/SidebarItems.tsx
- frontend/src/components/Inquiries/AddInquiry.tsx
- frontend/src/components/Themes/AddTheme.tsx
- frontend/src/components/Themes/ThemesTable.columns.ts
- frontend/src/components/Themes/ThemesTable.tsx
- frontend/src/hooks/useThemes.ts
- frontend/src/routeTree.gen.ts
- frontend/src/routes/_layout/themes.tsx
- frontend/src/utils/validation.ts
Created a frontend page and components for Themes. 
Extracted reusable logic and UI for the modal component. 
Added tests.
[Link to Ticket](https://incredihire-academy.atlassian.net/jira/software/c/projects/SR/boards/3?selectedIssue=SR-63)
> [SR-63] feat(frontend): add Themes page and components

- .vscode/launch.json
- README.md
Revising vscode launch.json to point to environment variable "PYTHON_POETRY_PATH" which can be found as output from `poetry env info`
> revise vscode instructions

- frontend/e2e/page-objects/InquiryPage.ts
- frontend/e2e/page-objects/helperBase.ts
- frontend/e2e/page-objects/pageManager.ts
- frontend/e2e/test-data/questions.json
- frontend/e2e/tests/auth.setup.ts
- frontend/e2e/tests/inquiry.spec.ts
- frontend/e2e/tests/login.spec.ts
- frontend/e2e/tests/sign-up.spec.ts
- frontend/playwright.config.ts
Refactored test structure by implementing the Page Object Model and relocating all .spec.ts files to the tests folder for better organization. Added inquiry.spec.ts to include all updates related to SR-16.
[Link to Ticket]
https://incredihire-academy.atlassian.net/jira/software/c/projects/SR/boards/3?selectedIssue=SR-16
https://incredihire-academy.atlassian.net/jira/software/c/projects/SR/boards/3?selectedIssue=SR-124
As an Admin, I want to publish a set of Inquiries that will be presented to users, to collect details on users’ state of mind, etc., so that users and managers can align state of mind details with team and individual activities.  
ACCEPTANCE CRITERIA
Admin portal should have a button that allows the admin to add an …
> SR-16/SR-124 Playwright framework setup and create inquiries

- frontend/e2e/page-objects/InquiryPage.ts
- frontend/e2e/tests/auth.setup.ts
- frontend/e2e/tests/inquiry.spec.ts
- frontend/playwright.config.ts
Dont run playwright tests in parallel mode temporarily disable auth.setup.ts
> Playwright auth spike

- backend/app/api/routes/auth.py
- backend/app/core/config.py
- backend/app/core/security.py
- backend/poetry.lock
- backend/pyproject.toml
- frontend/src/client/core/request.ts
- frontend/src/hooks/useAuth.ts
set auth cookie domain to root domain
fix refresh token cookie expiration extension logic 
fix refresh token behavior on frontend in local dev mode
https://incredihire-academy.atlassian.net/browse/SR-131
> SR-131 Implement PKCE and JWT refresh token flow cookie domain bugfix

- frontend/package-lock.json
Just updating an outdated, security-flagged package
> npm audit fix of an outdated package

- .github/workflows/infra-setup.yml
- infra/BillingAlert.tf
- infra/ecr.tf
- infra/main.tf
- infra/modules/alb/main.tf
- infra/modules/alb/outputs.tf
- infra/modules/alb/variables.tf
- infra/modules/ecs/main.tf
- infra/modules/ecs/outputs.tf
- infra/modules/ecs/variables.tf
- infra/modules/iam/main.tf
- infra/modules/iam/outputs.tf
- infra/modules/nat-gateway/main.tf
- infra/modules/nat-gateway/variables.tf
- infra/modules/vpc/main.tf
- infra/modules/vpc/outputs.tf
- infra/modules/vpc/variables.tf
- infra/provider.tf
- infra/state.tf
- infra/variables.tf
Creates and configures a one-time infrastructure setup in AWS using Terraform. This includes provisioning the VPC, subnets, RDS, ECR, ECS Fargate, and AWS cost alerts. Also, enables CloudWatch logs and configures GitHub Actions for on-demand IaC execution. Stores the Terraform state file securely in an S3 bucket.
[Link to Ticket] : https://incredihire-academy.atlassian.net/browse/SR-28 
Acceptance criteria:
Continuous integration: 
Tests are run for every PR to the main branch (github actions)
Deployment: 
Push code to the cloud (aws staging)
Ability to roll back effectively
Security: 
Only the resources that need to be accessible by public IP are …
> infra setup

- .github/workflows/infra-setup.yml
> temporarily hardcoding region

- .github/workflows/infra-setup.yml
Changing Terraform version to latest in their Github
> Terraform version

- .github/workflows/infra-setup.yml
- infra/main.tf
- infra/modules/alb/main.tf
- infra/modules/ecs/survey-backend-task-definition.json
- infra/state.tf
- infra/variables.tf
> Ramki11 patch 1

- frontend/src/hooks/useAuth.ts
change frontend login URL to use OpenAPI.BASE instead of frontend domain
> SR-139 Investigate connectivity issues between frontend and backend on local dev env

- frontend/src/client/core/request.ts
- frontend/src/hooks/useAuth.ts
- frontend/src/main.tsx
> Adding more console.log-based debugging

- .github/workflows/infra-setup.yml
- infra/modules/ecs/survey-backend-task-definition.json
Updated to taint the Service and task definition so the workflow will deploy for every push
Updated to the task definition to reflect the domain name, CORS and First token
> Infra patch3

- .github/workflows/infra-setup.yml
> comment out taint for now.

- infra/main.tf
- infra/modules/ecs/main.tf
- infra/modules/ecs/survey-backend-task-definition.json
- infra/modules/ecs/survey-frontend-task-definition.json
Updated image url and Image tag as parameters for task definition
Updated the Outh to read from SM
> Infra patch5

- infra/modules/ecs/survey-backend-task-definition.json
- infra/modules/ecs/survey-frontend-task-definition.json
> moving the google ids from frontend to backend task definitions

- backend/app/core/security.py
- infra/modules/ecs/survey-backend-task-definition.json
- infra/modules/ecs/survey-frontend-task-definition.json
> Correct redirects

- frontend/__tests__/inquiry/inquiries_table.test.tsx
- frontend/src/components/Inquiries/InquiriesTable.columns.tsx
- frontend/src/components/ScheduledInquiries/InquiryManagement.tsx
SR-57 refactored, renamed file, added delete pop-up, a test
[Link to Ticket](https://incredihire-academy.atlassian.net/jira/software/c/projects/SR/boards/3?selectedIssue=SR-57)
> SR-57 refactored, renamed file, added delete pop-up, a test

- frontend/e2e/page-objects/CategoriesPage.ts
- frontend/e2e/page-objects/InquiryPage.ts
- frontend/e2e/page-objects/ScheduleSettingsPage.ts
- frontend/e2e/page-objects/pageManager.ts
- frontend/e2e/test-data/constants.ts
- frontend/e2e/tests/categories.spec.ts
- frontend/e2e/tests/inquiry.spec.ts
- frontend/e2e/tests/schedule-questions-settings.spec.ts
- frontend/e2e/tests/updateinquiry.spec.ts
SR-128 Add Schedule Setting button and pop-up window
https://incredihire-academy.atlassian.net/jira/software/c/projects/SR/boards/3?selectedIssue=SR-128
SR-61 Add DateTime to Scheduled column
https://incredihire-academy.atlassian.net/jira/software/c/projects/SR/boards/3?selectedIssue=SR-61
SR-48
https://incredihire-academy.atlassian.net/jira/software/c/projects/SR/boards/3?selectedIssue=SR-48
Playwright scripts added for above Slices
> SR-128 SR-61 SR-48 Playwright scripts

- frontend/README.md
- frontend/src/initOpenAPI.ts
- infra/modules/ecs/survey-backend-task-definition.json
- infra/modules/ecs/survey-frontend-task-definition.json
OIDC-related updates to the backend configuration
> Updating OAUTH env variables to use OIDC

- .github/workflows/cdk-deploy.yml
> more gh workflow fixes

- .github/workflows/cdk-deploy.yml
> couple more gh workflow tweaks

- .github/workflows/cdk-deploy.yml
> installing the cdk manually

- .github/workflows/cdk-deploy.yml
> Fixing the way bootstrap initializes the AWS* variables
